# Generated by Django 3.2.11 on 2022-01-20 13:32

import django.core.validators
from django.db import migrations, models


def add_sample_movies(apps, schema_editor):
    Movie = apps.get_model("movie_collection", "Movie")
    db_alias = schema_editor.connection.alias
    Movie.objects.using(db_alias).bulk_create([
        Movie(title="Back to the Future", year=1985, rating=5),
        Movie(title="Who Framed Roger Rabbit", year=1988, rating=4),
        Movie(title="Phantom of the Paradise", year=1974, rating=4),
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1895), django.core.validators.MaxValueValidator(2050)])),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')])),
            ],
        ),
        migrations.RunPython(add_sample_movies, migrations.RunPython.noop)
    ]
