# Generated by Django 3.2.12 on 2022-09-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
